### ISSUE TITLE
SME Review Checklist

### ISSUE THREAD

**Issue by justineechen** [OpenLiberty/draft-guide-microservices-docker#6]
SME Review:

Review of the guide by a Subject Matter Expert (SME) for technical accuracy and content.

- [x] Ensure technical accuracy for code
- [x] Ensure technical accuracy for guide
- [x] Ensure technical accuracy for overall content
